version: '3.9'

services:
  openhim-mediator-data-stream:
    image: ghcr.io/i-tech-uw/openmrs-fhir-analytics/streaming-binlog:latest
    container_name: streaming-pipeline
    healthcheck:
      test: "exit 0"
    #volumes:
      # data is the directory which you want to persist the generated parquet files
      # - ./configs/streaming-pipeline/parquet:/tmp
    environment:
      - OPENMRS_URL=http://isanteplus:8080/openmrs
      - OPENMRS_USERNAME=${IPLUS_ADMIN_USER-Admin}
      - OPENMRS_PASSWORD=${IPLUS_ADMIN_PW-Admin123}
      - SINK_URL=${OPENHIM_STREAMING_SINK_URL-https://openhim-ssl.sedish-haiti.org/SHR/fhir}
      - SINK_USERNAME=${OPENHIM_STREAMING_CLIENT-streaming}
      - SINK_PASSWORD=${OPENHIM_STREAMING_PW-streaming}
      - JDBC_FETCH_SIZE=10000
      - JDBC_MAX_POOL_SIZE=50
      - JDBC_INITIAL_POOL_SIZE=10
      - JDBC_DRIVER_CLASS=com.mysql.cj.jdbc.Driver
      # the 2 variable below should be same as volume mappings above
      - PARQUET_PATH=
      - FHIR_DEBEZIUM_CONFIG_PATH=/deployments/config.json
    networks:
      - default
      - isanteplus
      - openhim
    configs:
      - source: pipeline-config
        target: /deployments/config.json

networks:
  isanteplus:
    external: true
    name: isanteplus
  openhim:
    name: openhim
    external: true
  default: