name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [published]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Pull containers
        run: docker-compose pull
      
      - name: Cache containers
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Start all containers
        run: docker-compose up -d
              - name: Sleep for 120 seconds
        run: sleep 120
        shell: bash

      - name: Display docker logs for openhim config
        run: docker-compose logs openhim-config

      - name: Show docker logs for isanteplus
        run: docker logs isanteplus

      - name: Wait For OpenMRS
        run: docker-compose --profile=utility up  --exit-code-from wait-for-openmrs wait-for-openmrs

      - name: Restart streaming pipeline
        run: docker-compose up -d --force-recreate streaming-pipeline
      
      - name: Sleep for 30 seconds
        run: sleep 30
        shell: bash
      
      - name: Run Basic API Tests (https://www.postman.com/itechuw/workspace/haiti-sedish/collection/1525496-192e3c9f-caea-4056-8077-b67af442f01c)
        env:
          POSTMAN_COLLECTION: https://www.getpostman.com/collections/22647ce67595a103f9c1
        run: docker-compose -f test.docker-compose.yml up --exit-code-from newman newman
               
      - name: Run iSantePlus QA Framework (https://github.com/IsantePlus/isanteplus-qaframework)
        run: docker-compose -f test.docker-compose.yml up --exit-code-from qa qa
        continue-on-error: false
      
